name: comac-recruit-info-spider

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necessary for uploading to releases
      actions: read

    steps:
      - uses: actions/checkout@v2

      - name: Get latest release
        id: get-latest-release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "draft|prerelease"  # Exclude drafts and prereleases
          view_top: 1  # Number of latest releases to fetch

      - name: Test Upload files to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.py
          tag: ${{ steps.get-latest-release.outputs.tag_name }}
          overwrite: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: install playwright's browser
        run: |
          python -m playwright install

      - name: run spider script
        run: |
          python3 main.py

      - name: Upload files to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: outputs/*
          tag: ${{ steps.get-latest-release.outputs.tag_name }}
          overwrite: true
