name: comac-recruit-info-spider

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: install playwright's browser
        run: |
          python -m playwright install

      - name: run spider script
        run: |
          python3 main.py

      - name: Upload files to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: output/*
          tag: ${{ github.ref }}
          overwrite: true
